// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ChargeStationInstallCertificatesCertificatesStatus.
const (
	Accepted ChargeStationInstallCertificatesCertificatesStatus = "Accepted"
	Pending  ChargeStationInstallCertificatesCertificatesStatus = "Pending"
	Rejected ChargeStationInstallCertificatesCertificatesStatus = "Rejected"
)

// Defines values for ChargeStationInstallCertificatesCertificatesType.
const (
	CSMS ChargeStationInstallCertificatesCertificatesType = "CSMS"
	MF   ChargeStationInstallCertificatesCertificatesType = "MF"
	MO   ChargeStationInstallCertificatesCertificatesType = "MO"
	V2G  ChargeStationInstallCertificatesCertificatesType = "V2G"
)

// Defines values for ChargeStationRuntimeDetailsOcppVersion.
const (
	N16  ChargeStationRuntimeDetailsOcppVersion = "1.6"
	N201 ChargeStationRuntimeDetailsOcppVersion = "2.0.1"
)

// Defines values for ChargeStationTriggerTrigger.
const (
	BootNotification               ChargeStationTriggerTrigger = "BootNotification"
	SignChargingStationCertificate ChargeStationTriggerTrigger = "SignChargingStationCertificate"
	SignCombinedCertificate        ChargeStationTriggerTrigger = "SignCombinedCertificate"
	SignV2GCertificate             ChargeStationTriggerTrigger = "SignV2GCertificate"
	StatusNotification             ChargeStationTriggerTrigger = "StatusNotification"
)

// Defines values for ConnectorFormat.
const (
	CABLE  ConnectorFormat = "CABLE"
	SOCKET ConnectorFormat = "SOCKET"
)

// Defines values for ConnectorPowerType.
const (
	AC1PHASE ConnectorPowerType = "AC_1_PHASE"
	AC3PHASE ConnectorPowerType = "AC_3_PHASE"
	DC       ConnectorPowerType = "DC"
)

// Defines values for ConnectorStandard.
const (
	CHADEMO            ConnectorStandard = "CHADEMO"
	CHAOJI             ConnectorStandard = "CHAOJI"
	DOMESTICA          ConnectorStandard = "DOMESTIC_A"
	DOMESTICB          ConnectorStandard = "DOMESTIC_B"
	DOMESTICC          ConnectorStandard = "DOMESTIC_C"
	DOMESTICD          ConnectorStandard = "DOMESTIC_D"
	DOMESTICE          ConnectorStandard = "DOMESTIC_E"
	DOMESTICF          ConnectorStandard = "DOMESTIC_F"
	DOMESTICG          ConnectorStandard = "DOMESTIC_G"
	DOMESTICH          ConnectorStandard = "DOMESTIC_H"
	DOMESTICI          ConnectorStandard = "DOMESTIC_I"
	DOMESTICJ          ConnectorStandard = "DOMESTIC_J"
	DOMESTICK          ConnectorStandard = "DOMESTIC_K"
	DOMESTICL          ConnectorStandard = "DOMESTIC_L"
	GBTAC              ConnectorStandard = "GBT_AC"
	GBTDC              ConnectorStandard = "GBT_DC"
	IEC603092Single16  ConnectorStandard = "IEC_60309_2_single_16"
	IEC603092Three16   ConnectorStandard = "IEC_60309_2_three_16"
	IEC603092Three32   ConnectorStandard = "IEC_60309_2_three_32"
	IEC603092Three64   ConnectorStandard = "IEC_60309_2_three_64"
	IEC62196T1         ConnectorStandard = "IEC_62196_T1"
	IEC62196T1COMBO    ConnectorStandard = "IEC_62196_T1_COMBO"
	IEC62196T2         ConnectorStandard = "IEC_62196_T2"
	IEC62196T2COMBO    ConnectorStandard = "IEC_62196_T2_COMBO"
	IEC62196T3A        ConnectorStandard = "IEC_62196_T3A"
	IEC62196T3C        ConnectorStandard = "IEC_62196_T3C"
	NEMA1030           ConnectorStandard = "NEMA_10_30"
	NEMA1050           ConnectorStandard = "NEMA_10_50"
	NEMA1430           ConnectorStandard = "NEMA_14_30"
	NEMA1450           ConnectorStandard = "NEMA_14_50"
	NEMA520            ConnectorStandard = "NEMA_5_20"
	NEMA630            ConnectorStandard = "NEMA_6_30"
	NEMA650            ConnectorStandard = "NEMA_6_50"
	PANTOGRAPHBOTTOMUP ConnectorStandard = "PANTOGRAPH_BOTTOM_UP"
	PANTOGRAPHTOPDOWN  ConnectorStandard = "PANTOGRAPH_TOP_DOWN"
	TESLAR             ConnectorStandard = "TESLA_R"
	TESLAS             ConnectorStandard = "TESLA_S"
	UNKNOWN            ConnectorStandard = "UNKNOWN"
)

// Defines values for EvseStatus.
const (
	Available   EvseStatus = "Available"
	Charging    EvseStatus = "Charging"
	Faulted     EvseStatus = "Faulted"
	Finishing   EvseStatus = "Finishing"
	Occupied    EvseStatus = "Occupied"
	Reserved    EvseStatus = "Reserved"
	Unavailable EvseStatus = "Unavailable"
)

// Defines values for LocationParkingType.
const (
	ALONGMOTORWAY     LocationParkingType = "ALONG_MOTORWAY"
	ONDRIVEWAY        LocationParkingType = "ON_DRIVEWAY"
	ONSTREET          LocationParkingType = "ON_STREET"
	PARKINGGARAGE     LocationParkingType = "PARKING_GARAGE"
	PARKINGLOT        LocationParkingType = "PARKING_LOT"
	UNDERGROUNDGARAGE LocationParkingType = "UNDERGROUND_GARAGE"
)

// Defines values for RegistrationStatus.
const (
	PENDING    RegistrationStatus = "PENDING"
	REGISTERED RegistrationStatus = "REGISTERED"
)

// Defines values for TokenCacheMode.
const (
	ALLOWED        TokenCacheMode = "ALLOWED"
	ALLOWEDOFFLINE TokenCacheMode = "ALLOWED_OFFLINE"
	ALWAYS         TokenCacheMode = "ALWAYS"
	NEVER          TokenCacheMode = "NEVER"
)

// Defines values for TokenType.
const (
	ADHOCUSER TokenType = "AD_HOC_USER"
	APPUSER   TokenType = "APP_USER"
	OTHER     TokenType = "OTHER"
	RFID      TokenType = "RFID"
)

// Certificate A client certificate
type Certificate struct {
	// Certificate The PEM encoded certificate with newlines replaced by `\n`
	Certificate string `json:"certificate"`
}

// ChargeStation Represents a charge station.
type ChargeStation struct {
	// Base64SHA256Password The base64 encoded, SHA-256 hash of the charge station password
	Base64SHA256Password *string `json:"base64_SHA256_password,omitempty"`

	// Evses List of EVSEs available at the charge station.
	Evses *[]Evse `json:"evses"`

	// Id Unique identifier for the charge station.
	Id string `json:"id"`

	// InvalidUsernameAllowed If set to true then an invalid username will not prevent the charge station connecting
	InvalidUsernameAllowed *bool `json:"invalid_username_allowed,omitempty"`

	// LocationId Identifier for the location of the charge station.
	LocationId string `json:"location_id"`

	// SecurityProfile The security profile to use for the charge station: * `0` - unsecured transport with basic auth * `1` - TLS with basic auth * `2` - TLS with client certificate
	SecurityProfile int `json:"security_profile"`
}

// ChargeStationInstallCertificates The set of certificates to install on the charge station. The certificates will be sent
// to the charge station asynchronously.
type ChargeStationInstallCertificates struct {
	Certificates []struct {
		// Certificate The PEM encoded certificate with newlines replaced by `\n`
		Certificate string `json:"certificate"`

		// Status The status, defaults to Pending
		Status *ChargeStationInstallCertificatesCertificatesStatus `json:"status,omitempty"`
		Type   ChargeStationInstallCertificatesCertificatesType    `json:"type"`
	} `json:"certificates"`
}

// ChargeStationInstallCertificatesCertificatesStatus The status, defaults to Pending
type ChargeStationInstallCertificatesCertificatesStatus string

// ChargeStationInstallCertificatesCertificatesType defines model for ChargeStationInstallCertificates.Certificates.Type.
type ChargeStationInstallCertificatesCertificatesType string

// ChargeStationRuntimeDetails Represents charge station runtime details.
type ChargeStationRuntimeDetails struct {
	// OcppVersion OCPP version used with charge station.
	OcppVersion ChargeStationRuntimeDetailsOcppVersion `json:"ocpp_version"`
}

// ChargeStationRuntimeDetailsOcppVersion OCPP version used with charge station.
type ChargeStationRuntimeDetailsOcppVersion string

// ChargeStationSettings Settings for a charge station
type ChargeStationSettings map[string]string

// ChargeStationTrigger Trigger a charge station action
type ChargeStationTrigger struct {
	Trigger ChargeStationTriggerTrigger `json:"trigger"`
}

// ChargeStationTriggerTrigger defines model for ChargeStationTrigger.Trigger.
type ChargeStationTriggerTrigger string

// Connector defines model for Connector.
type Connector struct {
	Format ConnectorFormat `json:"format"`
	Id     string          `json:"id"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time         `json:"last_updated,omitempty"`
	MaxAmperage int32              `json:"max_amperage"`
	MaxVoltage  int32              `json:"max_voltage"`
	PowerType   ConnectorPowerType `json:"power_type"`
	Standard    ConnectorStandard  `json:"standard"`
}

// ConnectorFormat defines model for Connector.Format.
type ConnectorFormat string

// ConnectorPowerType defines model for Connector.PowerType.
type ConnectorPowerType string

// ConnectorStandard defines model for Connector.Standard.
type ConnectorStandard string

// Evse defines model for Evse.
type Evse struct {
	Connectors []Connector `json:"connectors"`
	EvseId     *string     `json:"evse_id"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time `json:"last_updated,omitempty"`

	// Status The current operational status of the EVSE.
	Status EvseStatus `json:"status"`

	// Uid Uniquely identifies the EVSE within the CPOs platform (and
	// suboperator platforms).
	Uid string `json:"uid"`
}

// EvseStatus The current operational status of the EVSE.
type EvseStatus string

// GeoLocation defines model for GeoLocation.
type GeoLocation struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// Location A charge station location
type Location struct {
	Address     string               `json:"address"`
	City        string               `json:"city"`
	Coordinates GeoLocation          `json:"coordinates"`
	Country     string               `json:"country"`
	CountryCode string               `json:"country_code"`
	Id          string               `json:"id"`
	Name        *string              `json:"name"`
	ParkingType *LocationParkingType `json:"parking_type"`
	PartyId     string               `json:"party_id"`
	PostalCode  *string              `json:"postal_code"`
}

// LocationParkingType defines model for Location.ParkingType.
type LocationParkingType string

// MeterValue defines model for MeterValue.
type MeterValue struct {
	SampledValues []SampledValue `json:"sampled_values"`
	Timestamp     string         `json:"timestamp"`
}

// Registration Defines the initial connection details for the OCPI registration process
type Registration struct {
	// Status The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
	// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
	// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
	// endpoints.
	Status *RegistrationStatus `json:"status,omitempty"`

	// Token The token to use for communicating with the eMSP (CREDENTIALS_TOKEN_A).
	Token string `json:"token"`

	// Url The URL of the eMSP versions endpoint. If provided the CSMS will act as the sender of the versions request.
	Url *string `json:"url,omitempty"`
}

// RegistrationStatus The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
// endpoints.
type RegistrationStatus string

// SampledValue defines model for SampledValue.
type SampledValue struct {
	Context       *string        `json:"context"`
	Location      *string        `json:"location"`
	Measurand     *string        `json:"measurand"`
	Phase         *string        `json:"phase"`
	UnitOfMeasure *UnitOfMeasure `json:"unit_of_measure,omitempty"`
	Value         float32        `json:"value"`
}

// Status HTTP status
type Status struct {
	// Error The error details
	Error *string `json:"error,omitempty"`

	// Status The status description
	Status string `json:"status"`
}

// Token An authorization token
type Token struct {
	// CacheMode Indicates what type of token caching is allowed
	CacheMode TokenCacheMode `json:"cache_mode"`

	// ContractId The contract ID (eMAID) associated with the token (with optional component separators)
	ContractId string `json:"contract_id"`

	// CountryCode The country code of the issuing eMSP
	CountryCode string `json:"country_code"`

	// GroupId This id groups a couple of tokens to make two or more tokens work as one
	GroupId *string `json:"group_id,omitempty"`

	// Issuer Issuing company, most of the times the name of the company printed on the RFID card, not necessarily the eMSP
	Issuer string `json:"issuer"`

	// LanguageCode The preferred language to use encoded as ISO 639-1 language code
	LanguageCode *string `json:"language_code,omitempty"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time `json:"last_updated,omitempty"`

	// PartyId The party id of the issuing eMSP
	PartyId string `json:"party_id"`

	// Type The type of token
	Type TokenType `json:"type"`

	// Uid The unique token id
	Uid string `json:"uid"`

	// Valid Is this token valid
	Valid bool `json:"valid"`

	// VisualNumber The visual/readable number/identification printed on an RFID card
	VisualNumber *string `json:"visual_number,omitempty"`
}

// TokenCacheMode Indicates what type of token caching is allowed
type TokenCacheMode string

// TokenType The type of token
type TokenType string

// Transaction defines model for Transaction.
type Transaction struct {
	ChargeStationId   string       `json:"charge_station_id"`
	EndedSeqNo        int          `json:"ended_seq_no"`
	IdToken           string       `json:"id_token"`
	MeterValues       []MeterValue `json:"meter_values"`
	Offline           bool         `json:"offline"`
	StartSeqNo        int          `json:"start_seq_no"`
	TokenType         string       `json:"token_type"`
	TransactionId     string       `json:"transaction_id"`
	UpdatedSeqNoCount int          `json:"updated_seq_no_count"`
}

// UnitOfMeasure defines model for UnitOfMeasure.
type UnitOfMeasure struct {
	Multipler int    `json:"multipler"`
	Unit      string `json:"unit"`
}

// ListChargeStationsParams defines parameters for ListChargeStations.
type ListChargeStationsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListLocationsParams defines parameters for ListLocations.
type ListLocationsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTransactionsByChargeStationParams defines parameters for ListTransactionsByChargeStation.
type ListTransactionsByChargeStationParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadCertificateJSONRequestBody defines body for UploadCertificate for application/json ContentType.
type UploadCertificateJSONRequestBody = Certificate

// RegisterChargeStationJSONRequestBody defines body for RegisterChargeStation for application/json ContentType.
type RegisterChargeStationJSONRequestBody = ChargeStation

// UpdateChargeStationJSONRequestBody defines body for UpdateChargeStation for application/json ContentType.
type UpdateChargeStationJSONRequestBody = ChargeStation

// InstallChargeStationCertificatesJSONRequestBody defines body for InstallChargeStationCertificates for application/json ContentType.
type InstallChargeStationCertificatesJSONRequestBody = ChargeStationInstallCertificates

// ReconfigureChargeStationJSONRequestBody defines body for ReconfigureChargeStation for application/json ContentType.
type ReconfigureChargeStationJSONRequestBody = ChargeStationSettings

// TriggerChargeStationJSONRequestBody defines body for TriggerChargeStation for application/json ContentType.
type TriggerChargeStationJSONRequestBody = ChargeStationTrigger

// RegisterLocationJSONRequestBody defines body for RegisterLocation for application/json ContentType.
type RegisterLocationJSONRequestBody = Location

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = Location

// RegisterPartyJSONRequestBody defines body for RegisterParty for application/json ContentType.
type RegisterPartyJSONRequestBody = Registration

// SetTokenJSONRequestBody defines body for SetToken for application/json ContentType.
type SetTokenJSONRequestBody = Token

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload a certificate
	// (POST /certificate)
	UploadCertificate(w http.ResponseWriter, r *http.Request)
	// Delete a certificate
	// (DELETE /certificate/{certificate_hash})
	DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Lookup a certificate
	// (GET /certificate/{certificate_hash})
	LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// List Charge Stations
	// (GET /cs)
	ListChargeStations(w http.ResponseWriter, r *http.Request, params ListChargeStationsParams)
	// Register a new charge station
	// (POST /cs)
	RegisterChargeStation(w http.ResponseWriter, r *http.Request)
	// Delete Charge Station by ID
	// (DELETE /cs/{cs_id})
	DeleteChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Get Charge Station by ID
	// (GET /cs/{cs_id})
	LookupChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Update a charge station
	// (PUT /cs/{cs_id})
	UpdateChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Install certificates on the charge station
	// (POST /cs/{cs_id}/certificates)
	InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string)
	// Reconfigure the charge station
	// (POST /cs/{cs_id}/reconfigure)
	ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Get Charge Station runtime details
	// (GET /cs/{cs_id}/runtime-details)
	LookupChargeStationRuntimeDetails(w http.ResponseWriter, r *http.Request, csId string)

	// (POST /cs/{cs_id}/trigger)
	TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// List locations
	// (GET /location)
	ListLocations(w http.ResponseWriter, r *http.Request, params ListLocationsParams)
	// Registers a location with the CSMS
	// (POST /location)
	RegisterLocation(w http.ResponseWriter, r *http.Request)
	// Delete a location by ID
	// (DELETE /location/{locationId})
	DeleteLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Lookup a location by ID
	// (GET /location/{locationId})
	LookupLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Update a location
	// (PUT /location/{locationId})
	UpdateLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Registers an OCPI party with the CSMS
	// (POST /register)
	RegisterParty(w http.ResponseWriter, r *http.Request)
	// List authorization tokens
	// (GET /token)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Create/update an authorization token
	// (POST /token)
	SetToken(w http.ResponseWriter, r *http.Request)
	// Lookup an authorization token
	// (GET /token/{token_uid})
	LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string)
	// List transactions by charge station
	// (GET /transactions/{cs_id})
	ListTransactionsByChargeStation(w http.ResponseWriter, r *http.Request, csId string, params ListTransactionsByChargeStationParams)
	// Find a transaction
	// (GET /transactions/{cs_id}/{transaction_id})
	LookupTransaction(w http.ResponseWriter, r *http.Request, csId string, transactionId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Upload a certificate
// (POST /certificate)
func (_ Unimplemented) UploadCertificate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a certificate
// (DELETE /certificate/{certificate_hash})
func (_ Unimplemented) DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup a certificate
// (GET /certificate/{certificate_hash})
func (_ Unimplemented) LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Charge Stations
// (GET /cs)
func (_ Unimplemented) ListChargeStations(w http.ResponseWriter, r *http.Request, params ListChargeStationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new charge station
// (POST /cs)
func (_ Unimplemented) RegisterChargeStation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Charge Station by ID
// (DELETE /cs/{cs_id})
func (_ Unimplemented) DeleteChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Charge Station by ID
// (GET /cs/{cs_id})
func (_ Unimplemented) LookupChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a charge station
// (PUT /cs/{cs_id})
func (_ Unimplemented) UpdateChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Install certificates on the charge station
// (POST /cs/{cs_id}/certificates)
func (_ Unimplemented) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reconfigure the charge station
// (POST /cs/{cs_id}/reconfigure)
func (_ Unimplemented) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Charge Station runtime details
// (GET /cs/{cs_id}/runtime-details)
func (_ Unimplemented) LookupChargeStationRuntimeDetails(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /cs/{cs_id}/trigger)
func (_ Unimplemented) TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List locations
// (GET /location)
func (_ Unimplemented) ListLocations(w http.ResponseWriter, r *http.Request, params ListLocationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Registers a location with the CSMS
// (POST /location)
func (_ Unimplemented) RegisterLocation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a location by ID
// (DELETE /location/{locationId})
func (_ Unimplemented) DeleteLocation(w http.ResponseWriter, r *http.Request, locationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup a location by ID
// (GET /location/{locationId})
func (_ Unimplemented) LookupLocation(w http.ResponseWriter, r *http.Request, locationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a location
// (PUT /location/{locationId})
func (_ Unimplemented) UpdateLocation(w http.ResponseWriter, r *http.Request, locationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Registers an OCPI party with the CSMS
// (POST /register)
func (_ Unimplemented) RegisterParty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List authorization tokens
// (GET /token)
func (_ Unimplemented) ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create/update an authorization token
// (POST /token)
func (_ Unimplemented) SetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup an authorization token
// (GET /token/{token_uid})
func (_ Unimplemented) LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List transactions by charge station
// (GET /transactions/{cs_id})
func (_ Unimplemented) ListTransactionsByChargeStation(w http.ResponseWriter, r *http.Request, csId string, params ListTransactionsByChargeStationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Find a transaction
// (GET /transactions/{cs_id}/{transaction_id})
func (_ Unimplemented) LookupTransaction(w http.ResponseWriter, r *http.Request, csId string, transactionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadCertificate operation middleware
func (siw *ServerInterfaceWrapper) UploadCertificate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCertificate(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCertificate operation middleware
func (siw *ServerInterfaceWrapper) DeleteCertificate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "certificate_hash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithOptions("simple", "certificate_hash", chi.URLParam(r, "certificate_hash"), &certificateHash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificate_hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCertificate(w, r, certificateHash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupCertificate operation middleware
func (siw *ServerInterfaceWrapper) LookupCertificate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "certificate_hash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithOptions("simple", "certificate_hash", chi.URLParam(r, "certificate_hash"), &certificateHash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificate_hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupCertificate(w, r, certificateHash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChargeStations operation middleware
func (siw *ServerInterfaceWrapper) ListChargeStations(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChargeStationsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChargeStations(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterChargeStation operation middleware
func (siw *ServerInterfaceWrapper) RegisterChargeStation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterChargeStation(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChargeStation operation middleware
func (siw *ServerInterfaceWrapper) DeleteChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupChargeStation operation middleware
func (siw *ServerInterfaceWrapper) LookupChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChargeStation operation middleware
func (siw *ServerInterfaceWrapper) UpdateChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// InstallChargeStationCertificates operation middleware
func (siw *ServerInterfaceWrapper) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstallChargeStationCertificates(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ReconfigureChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReconfigureChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupChargeStationRuntimeDetails operation middleware
func (siw *ServerInterfaceWrapper) LookupChargeStationRuntimeDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupChargeStationRuntimeDetails(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerChargeStation operation middleware
func (siw *ServerInterfaceWrapper) TriggerChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLocationsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocations(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterLocation operation middleware
func (siw *ServerInterfaceWrapper) RegisterLocation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterLocation(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLocation operation middleware
func (siw *ServerInterfaceWrapper) DeleteLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLocation(w, r, locationId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupLocation operation middleware
func (siw *ServerInterfaceWrapper) LookupLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupLocation(w, r, locationId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLocation operation middleware
func (siw *ServerInterfaceWrapper) UpdateLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLocation(w, r, locationId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterParty operation middleware
func (siw *ServerInterfaceWrapper) RegisterParty(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterParty(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SetToken operation middleware
func (siw *ServerInterfaceWrapper) SetToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetToken(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupToken operation middleware
func (siw *ServerInterfaceWrapper) LookupToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "token_uid" -------------
	var tokenUid string

	err = runtime.BindStyledParameterWithOptions("simple", "token_uid", chi.URLParam(r, "token_uid"), &tokenUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token_uid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupToken(w, r, tokenUid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactionsByChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ListTransactionsByChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsByChargeStationParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactionsByChargeStation(w, r, csId, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupTransaction operation middleware
func (siw *ServerInterfaceWrapper) LookupTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "cs_id" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "cs_id", chi.URLParam(r, "cs_id"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cs_id", Err: err})
		return
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", chi.URLParam(r, "transaction_id"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupTransaction(w, r, csId, transactionId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/certificate", wrapper.UploadCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/certificate/{certificate_hash}", wrapper.DeleteCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/certificate/{certificate_hash}", wrapper.LookupCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs", wrapper.ListChargeStations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs", wrapper.RegisterChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cs/{cs_id}", wrapper.DeleteChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{cs_id}", wrapper.LookupChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/cs/{cs_id}", wrapper.UpdateChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{cs_id}/certificates", wrapper.InstallChargeStationCertificates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{cs_id}/reconfigure", wrapper.ReconfigureChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{cs_id}/runtime-details", wrapper.LookupChargeStationRuntimeDetails)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{cs_id}/trigger", wrapper.TriggerChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/location", wrapper.ListLocations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location", wrapper.RegisterLocation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/location/{locationId}", wrapper.DeleteLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/location/{locationId}", wrapper.LookupLocation)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/location/{locationId}", wrapper.UpdateLocation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.RegisterParty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token", wrapper.ListTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/token", wrapper.SetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token/{token_uid}", wrapper.LookupToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/transactions/{cs_id}", wrapper.ListTransactionsByChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/transactions/{cs_id}/{transaction_id}", wrapper.LookupTransaction)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PbOJb+KyjuPiRbtCXLbu/GL7OKpDia2JZLUtI1M07RMAlJGJMAGwDlaFz+71MH",
	"ICmQhC7pHnc76bx0iyQuBwffueLAefRCnqScEaakd/boyXBBEqx/9ohQdEZDrAg8RkSGgqaKcuadeV0U",
	"xpQwhUKrle+lgqfwgugRwm0jTBcEXQ8uEWEhj0hkD4QeqFogRh5iyohEgqQxDkmE7lbo9uaG3Xq+p1Yp",
	"8c48qQRlc+/pyfcE+SWjgkTe2T8qE38uG/O7f5JQeU++11tgMScThQ0tddLGJBVEAksQRqFui6RpfNhY",
	"5B2W5PQkmLzvdn46DVIs5QMXkXu9pm2xZB9N3ncPOj+dogWWC8RnSC1IbT5UDuh7Cf5yQdhcLbyz05MG",
	"C3yPLKUhqTrxBZUKBh98mgwkwktMY3wXE4SVYz5YH1Uk0eP8tyAz78z7r9YaI60cIK3BUhKYlGWxHs47",
	"UyIjJVVYCLyC79TBio+M/pIRRCPCYJuIQDMuNhDTWCVlSxzTKMgkEQwnJMBxzB+IY5rhDEmikOIISIPx",
	"GcIM5QOgYgD0QOMYMa5QKsgSMO3YhpAzRkIFNJQ03XEeE8yAqJiHul3gWu6wuc6ivXvTneuWJMwEVasg",
	"FXxG4w0SVbRCeStYfSbJBgafof9Bt+1bdIAypnuSCCmBmUy5UEYK77CkIcKZWkDbI2g7vZi4vnUq35rq",
	"4Yatl0WZInMiGoJLAeeNlVb5u1Ogh0wqHMeW/pKbmKUFw6JRAr+o6Y84c+0Ngp6VLho/dzAcUzcM4NbE",
	"D5YrFi4EZzyT8epQ82KjstTPpRR+Ld1/oBr2PVhvtols/c1HEZnhLFaa5mvCIiNUhGUJQKAbhiRVBIAw",
	"JrC/+mfR7rNjTvPisRzhU+fc873LEfznned7vcnlxNGxBj391d9pOqr6bbPdkbtxOs6YognpE4VpLLea",
	"oRqahOmJItO1aZR4mKbBkgjptG+j3vU1yr+CdohykW0ooYKjR4ennu91DtuHR7sZWZl7JxMmRIFW1VTj",
	"KKLwDsfXldU0oXRPVohKLWhahedqVJrBDtE7LpBepaZ53U4ueBZHaIGX2h6gGQfjQdkcpVgpItjZDbvJ",
	"2u3jsDR5+pG0zNslFhSsnXmZ64KipZki1CYmjLOIgLXhqVmR1UzLKQtzkjCLEFhuRKMbJkmKBVZGyCRJ",
	"6EHIY86kmamYfftEZavmPFgpQe8y0MWwK2j7dAn+QpMsQbF2OrQJ0Tw9OjwF5v/UbmvI4FARIY1Ks1yU",
	"o3a77RDW6l4Wu68Hr/ta3i7sTAWdgxVpQsR8aIyIcJgPXBUXtR6ogPxbztUVz6XZ9Jlo/VV/SefsU+e8",
	"V3GD4aWmlLJ5TqujAU/uKCNRz6lxNmmpnFKnXBkfhet1VBc44yLByl7fZNT7MJiCduy+vRg49arxZRqv",
	"YyxVkKUR4MYtnfBJi5cgIRcResASQS+U90Kv6JxxcDbAsxIEK9Iyn16D0vmCkxT8G6/T7pwcHHUOOv87",
	"Peqctdtn7fbfPb9cjAc9DkARuixRgr8EOEmJwHNiswB8j+OOwxUxXZY8Vvv3SPkDEUHdAHV7wVFw/b47",
	"GXg+PByXD/2ek9MgpxE2UUMxSO99tz/QRqz3vjv66xB6jy4Hk+mwF3Tth7f2Q89+6NsPA/vhnf1wbj+8",
	"tx8qk/7VfvhgP1x4vnf+dhp0e/mPPvwYDnrBafu4/SboBJKyeUyCo9Pae7UQZONrzfPm69OT4nXn6M1p",
	"MD2qPQa90eXbUfVlp/boanPcrT3DIq4Gl93gp6DTLn6fBsfW75/K30dt68NR2/5yYn85MV+uu1fT0fm4",
	"e/0+eDuaTkeXwcfr6uvp6Droj36+8nxvOphcdINx+Wvi+d7Hqw9X8HWnxshR7BvfuiIVVcRX0Gxh0qVq",
	"dPTX0DJhoYCqDuy2MHKts56asSOYxTyi2hBmfnNaaZt/HGZCgH8ALMW5MTftC/8GQnjbL+sWwbzne6Mw",
	"zFKa+82SiKX++Q48bf3rI8NW68I6QRPKqFzkzvV6mVaLxiqyzVF9vFrH9bIkWjuY1MRTveuRRGmMFXAM",
	"vcIM/J7szqyai/KTfH24M9GTmYDRMNW3AehC7TnhF3kg2QRvjBVVWVTV/LOYa9lpwo2z+d7Na0SXM9nD",
	"uOi1iW2k36qOTREgN1wbHEWCSOm05CFVK/cHzkVEWRGKbhNgm6e6Z8aU2DSq/hZAoOlsYFBl+ZCd/3Ow",
	"HrzZvVRCisU9ZfOmeb4YXZ0Hl6PpaPxz929a644/DK/Og/PuuHs+sF5cjMBDGl0F/fHw08A0Hl0Fk+l4",
	"oH2nj1f9wfh8PPp41S86f/b3Ikytgg3uVcohii+ZtGMwV/6k2PJ8g9ebUtuC6j5bZLmweEkUEZ9wnDn0",
	"vtQ6IwqW8Hl/3T8x3cygDvUPOlQqnKQOPtXWXaPA7utazJjMqVRig3D1yUwnPEBZUUYV1dGbyf9xVgTd",
	"ZUpt1LseImGNiFLBQ7MBNT7tTI4Uir4yHCyUSHWIhsVH/QwxWILFPYkQluh2PDgfTqaD8aB/a1Kd0FTx",
	"e8LKBFWeKUWK37A7YiJ/xREOgVr4igiLUk514nvJaQSBsY6dCYl2r3c7gTfs9npw1R9enbvp4yxeVYks",
	"CIOGty0eprSVpxXkrV+86Rx2bnVsu35uhYJoE4RjeXvDyjWZELXQAjkxYC5LzrnTS0Cje9MM+VaKNeRJ",
	"kjEdHbK5yaoA9eRyco1e9caD/uBqOuxeTILp6MPgKuhqE7crr5+J2D39x/FFARg9Q8Gdchv1jqSCL2kE",
	"HAXjO7mcGH7jUMG2mLQJi4gohipHKXBnOzeZoDvtm2GYS+4qEu9yHxX5ovZz9yzTuLNxQrDMBGb7eZLp",
	"Asv9DEzGqAr4LDDjk1367iOjajS7zBs/+d6y4EM+MsuSO0dS3DRz8nODQnk/nV6j0iuqcpkIwYUbT/pT",
	"od9+XXYX2R92ASUfzrWyqVvoukwfN3BB/2VUj8FaI+ONwwUJktyE1k5jWFTk7RdYIZ0HA+RrUYaOILlU",
	"FnrI9rYvfu7+DWKv7sXF6OdBf/0rGL17dzG8Gugo79Ng7NQjAG+BQ+U8IzKJRNMADfvoFbnsDvuvEZaS",
	"h1SHJ6U2MaS+0s+O9GKe1ONCvtZGXec1vTPv1T+6B3/HB//6/Nh5ev3q4C+v1y+Oqy/aB28+P75pvnv9",
	"F8/f7da5FqZbIGhRaBkqZQacBsVV1YEd30sos54aM84Fz9INbKQS0QjpFvr0lmdpvN5gfeaQ4HuC1ANH",
	"XKCEC1J8euDiHlQiZ6RK0fGpKzsmZebKPQ7zhcGGYLbyUcLN+aveOnBLGmnrvClKBWXKxJ/wevxu2Ech",
	"FpGvTycZAWuIBY1Xpcp3hiaYzTM8J1s2JBVkRgSEukXjwogVx0BYouFkhE6P3xwcrRvlbuNXbdZzB+b7",
	"xd22y+3gB3wF3OwE53FlvcdbTqMc3oKtamy90g/ej3rBx8lgDCrl+rr4OZq+1/8HIDhVSrZpQZk5YTea",
	"gkZ7wFmfibvQjBTIlBnJNHIdgC+pzHAc5BbMSZNp0hIER+YQQ7dtFdmCsPAlSxnAbC0Cu0s+qpFNud9+",
	"cbBnUgW2Ei5luFi9bxsOp1USmMn8DKHpvuiIPMgj8k3hHbhaUSDJLwHjVgMrp0yjoHQ5Ha6MIuJrAy0r",
	"dnOEWXw2iymz/RBrX6XCQm0lV9NaxthNcVizbBNLcjHPZwn0Trrmqu94g9+N2SxmVgit8bG2zNombSBw",
	"zTgXUqq+XgMrSRYrmsZGVJo8Bcdyd9CrW/nWWE1CnnTBzIwX7jUOzSFQgmnsnXkJJktyoAhO/l8teDZf",
	"KLCB8jDkiVckWrxLPPhEEDRqnt8NGTgXOEbd66EpQVBEuzCls2J6Q9jhI/Ilb22KQ2RxHAuGB6JKiDRi",
	"GhKW+99m/m4KQok6h22TFFDxmip9tO975Um31z5sm3Y8JQyn1DvzjvUr7QktNPNbtYKIlEvlSGemMceR",
	"9iEapSwoL/KA6c1ZqY6rQqyP041Nr7YGrxX0nCmEcRSIZBIMTpKpDMemiqaIkeGhTAlLhAVBdwQaA/44",
	"jvJYGcHvgzscYxYSYWLdstswKldUPYjMY7y3PFqVIZiRPpymca6UW/+URuEZhbIzp2/N8FQFLQRS+oVM",
	"Ocur1Trtoyb3e9rMRwZxulzkP0ZeHjRpyuoZbPIl1RUnJhTSEiezJMFiVfIPAFFhocJz2Sg6hJ42zlqP",
	"1kOwwHLxZBYdE1dVTl+/3wQ+iFsWWKI7QhjK0jUIygjfoAnXCg4r9YY3LHd2+oMxulspIl2YMYRUMQPh",
	"hdafsOxHjwLBIFxrlVFfq1fHgG/t1fb0x9PnBlxOmvy64qjAxpPvnZgmz4yWK67QjGfsZYHUbNieIPW9",
	"OXGovgvO77P0jwefoeNlga/9fGqypgEtphcpmT85tte43FcB601zYnxMlKBkCZIS5wXSVYssjQ+T4jll",
	"ZUFcDZ9UqkpBkmwCtBkHmbgHJtTOO4iOvKcpuiMzLvT0QmePFei0OCahyoNjmcUKSaITshr3v2REn+rk",
	"wOezmSTgEVrwpowmEGW2XaW3m6mTFfIEUZlgm6aNaUJrs5rCMV0D5q9pOHLQ8FsFbL8ig0q5f7OIs4HD",
	"7iZMvCxxABrN2pAFwFIcKvGR1vZuT9echsGmY8TIg7PgWa6kIkl+ciBlluSWoOnJ3jCwDowrtCLKWAl9",
	"AgEOOon0UY0eRRcTu0qlKdPubGoqfvVrcsMkR1RpD1sPGXI2o3NdsK4dZar0KQYs4Y5zBfOXOQWXaSnW",
	"XIXGM/nDVfh9Rx5xwUUncLZB0Sjn1mMoAxrt4QkjjGRKQtjSOlzuVogqiYb9w03Oa22LdyroOh7L6xuF",
	"Aqz5G9KkGvZyMhwVDft5uL0qUYZdL9L1rGok2J9hf7ta2m6gi/N2Pvt1KMi9yD8cBb+rb9lUOTvg9Ds7",
	"mB/ZPeMPrK4yXhKcz4n6FVhOM2cuSZ9xNMrRtYc5p0vC0DByZmyg37ehwF6E3XwREvSCElZO2O1vmFv1",
	"S2mFA1mFaXHhzmZZ5fbdnxSzrouI+8O4dmfrw4uCVr606h1E54XJr0CbIKVbvzkvP8lgtUQajzNvnxeD",
	"QESSnyncEaTZss5NNcMaKhHVocoNg4iU5YmsojQOQzQxJ4wIHDeuZRchjc7ak3CBGZWJD3EIjJqPdsNm",
	"XCDOzME/jMHmxBRWwfajKBM60ifSXFvrzsCZXrNBz+U7g6yipk8QiHdIhCTPS/XqXIGYSeF7gshsRkKF",
	"6EzfDBOZ3lzF3eFRuRM/rI99S/E7EV9rf3+jyJqbqAfR+hLrdm++dnX1P+nV1+7T/ql8/Nrad/srtX34",
	"4flv9/zr7NpfQqy7pW7vKb+s+kPPWjd6v2k1uxUZduHyVk0prZMJ8LSKjjKvvSfCrgnVlQiuIzQqVXE/",
	"58fpxIs8nbCvT+1/MFHC4eUdScQW3gpZKGG/3zFE+fdxdgK86HWxvgD3HFpqvUnfYfp+M8fdO2jrsdZj",
	"8WsY7VnSUnp75ZxrP29jCYq1v7tLANYk/UZv7cRVHBE2UvAnWxuyl10oYu9CJbtZkdmdtuord9X478+x",
	"q1992tJ+Ji2xETd1j/ubwk1ZhLEfbrbkw38FakzH300X/NF2pL0FHcWVim8URmVu2rq5vsHUFP7u5pyg",
	"ZciYuZ9qbnRUvQfUJ0VRQZGprCTK3BclbxihakFEfhVY01y5/VpOYubMb8kWBMQxesBUlbdnzXtdKp0P",
	"d8M2DbjL57mGsZ7J4alckf5OnZ7NWLHAyMOU5kAsr2W4qyapVOYWdXHVbIGLipX1Xev89uL6VGZD0KYv",
	"QP6I2F5kxGYup+4RrhV/etUA4uVFao67tHbQll/k3hixGfGWoPKy0qLnd+J/LfYnxED/mdRavnXfkT7r",
	"2RciQae5L0jX97TUZ61HczEqywuxtleE/8bdNeMUG7zbeStJ29fjd9xtfFaP38JTLVPT3IUfZdzVCOKr",
	"oLq+2FcpG9y3tlubZWsMCDOaf+/UYYatPm9XLz5H7/9wEF6Eg2DdE/6qrK4N0cOX5y9slyBbdC0GbBbg",
	"1mP1vu5eEl1mDKy+TVrQsK9Lze1Gm4+R7f36VqTaXtkuChrXol/GCXZFTFxiYa/RXGk+/P2Mp0XdC82h",
	"vKMsAp+sgt4NIqj/BQGx3AzqmIc4RhFZkpiniflDMtDey/8AlbdQKj1r6cR/vOBSnb05OWq3cEpby7bn",
	"xmjEw3si9hg0wQzPiagO+fnp3wEAAP//Vlz8FJ5kAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
